Update ru_RU.lang
CoFH/CoFHCore-1.12-Legacy pull request #62
Opened 2019-08-07 18:24 UTC by Bytegm

Mistakes are corrected

2019-08-07 19:21 UTC, CrossVas requested changes

2019-08-07 19:21 UTC, CrossVas commented on src/main/resources/assets/cofh/lang/ru_RU.lang
> +enchantment.cofhcore.multishot.desc=Лук будет стрелять дополнительными стрелами при каждым выстрелом. Потребляется только одна стрела.
при каждым выстрелом -> при каждом выстреле

2019-08-08 10:51 UTC, Bytegm commented on src/main/resources/assets/cofh/lang/ru_RU.lang
> +enchantment.cofhcore.multishot.desc=Лук будет стрелять дополнительными стрелами при каждым выстрелом. Потребляется только одна стрела.
Ok

2019-08-08 11:03 UTC, CrossVas commented on src/main/resources/assets/cofh/lang/ru_RU.lang
> +enchantment.cofhcore.multishot.desc=Лук будет стрелять дополнительными стрелами при каждым выстрелом. Потребляется только одна стрела.
При каждОм выстреле

2019-12-23 04:48 UTC, KingLemming commented
Handling manually. Thanks. :)

2019-12-23 04:48 UTC, closed without merging